### PR TITLE
Dll file version is missing

### PR DESCRIPTION
**Pull request by brucejia-china**
Hi Christine,

This may be a potential fix for an installer issue. The issue is: On some users' machines the file assimp.dll is failed to install.

Thanks,
Bruce Jia

### CODE REVIEW

**Comment by brucejia-china** [comment]
Hi Christine and Henrik, Could you please review and merge this request today?

**Comment by christinelehmann** [comment]
Hello Bruce,

looks like a reasonable change! But I guess there is a build error left:
"../../bin/unit: No such file or directory"

Could you please check this?

Best regards,
Christine

**Comment by brucejia-china** [comment]
Hi Christine,

I noticed that Travis CI build issue. That build happens on Linux platform and I'm trying to fix the issue.
On my Windows box it builds successfully for both debug and release configurations.

Questions:
1. do you have CI environment for Windows platforms?
2. Besides Travis CI do you have other build environments for *nix platforms?

Regards,
Bruce Jia

**Comment by christinelehmann** [comment]
Hi Bruce,

Ok, great!
To your questions:

1. do you have CI environment for Windows platforms?
No, I did not have any automatically build systems for windows. I tested manually using cmake/visual studio.
2. Besides Travis CI do you have other build environments for *nix platforms?
I tested on *nix platforms using Jenkins. After uploading a new version of Assimp and changing the hash in the CMakeLists.txt file, Jenkins reported errors/warnings on Linux, approx. every 20 minutes – as one build/compile creation steps takes that long ..

Best regards,
Christine

**Comment by brucejia-china** [comment]
Hi Christine,

More comments and questions here.
1.	I’m going to setup Jenkins build for assimp library on Windows. Wind WU promised to help on this. :)
2.	It’s great that you have *nix platforms to build Assimp and it’s also great to know the builds are managed by Jenkins. Really cool! Can you post the Jenkins links here then I can have a look?
3.	Today I set up a Ubuntu instance on ECS. So far I have built assimp311-14-11-26 branch successfully, including both lib/libassimp and bin/assimp. What frustrated me is that unit tests doesn’t build. Error message is as below.

[ERROR] CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CPPUNIT_LIBRARY
    linked by target "unit" in directory /home/administrator/work/git/brucejia-china/assimp/test

do you have idea to fix this? If I’m correct AssImp is using contrib/cppunit-1.12.1. According to contrib/cppunit_note.txt, this copy of cppunit library is different with official cppunit library. It’s bad that I failed to build this copy of cppunit.

4.	Another thing I find is that assimp team is using gtest rather than cppunit now. You can check their code online.
I think we need to evaluate if it’s worth to fix cppunit build errors.

Regards,
Bruce Jia

**Comment by christinelehmann** [comment]
Hi Bruce,

Here you can find the current Jenkins build results:
http://cipdm.ads.autodesk.com/view/InfraWorksMain/

I’m not quite sure what is the difference between libassimp and assimp. However, due to my last state of the assimp sources, I know that you only need to have a proper compilation of the assimp-library project to create the DLL and LIB file. For testing purposes, it is also nice to run the assimp-viewer project.

You do not need the assimp unit test project, which uses cppunit (or gtest) and thus leads to missing paths, as we do not have it per default. Hence, you could exclude it from the assimp solution.


Best regards,
Christine

**Pull request closed without merging**
